language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - gcc-6
    - g++-6
    - xorg-dev
    - cmake
    - cmake-data
script:
- mkdir build
- cd build
- CC=gcc-6 CXX=g++-6 cmake -DOGLTUTOR_STATIC=ON ..
- make
notifications:
  email: false
