language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - xorg-dev
before_script:
- wget https://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
- tar -xvf /tmp/cmake.tar.gz
- export PATH=$PWD/cmake-3.1.3-Linux-x86_64/bin:$PATH
script:
- mkdir build
- cd build
- CC=gcc-6 CXX=g++-6 cmake -DOGLTUTOR_STATIC=ON ..
- make
