language: cpp
addons:
  apt:
    sources: &required_sources
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages: &required_packages
    - cmake
    - cmake-data
matrix:
  include:
    # 64-bit Release
    # We can't set CC and CXX directly as Travis overrides them.
    - env: ACTUAL_CC=gcc-6 ACTUAL_CXX=g++-6 CONFIGURATION=Release
      addons:
        apt:
          sources:
          - *required_sources
          packages:
          - *required_packages
          - gcc-6
          - g++-6
          - libx11-dev
          - libxrandr-dev
          - libxinerama-dev
          - libxxf86vm-dev
          - libxcursor-dev
          - x11proto-kb-dev
    # 32-bit Release
    - env: ACTUAL_CC="gcc-6 -m32" ACTUAL_CXX="g++-6 -m32" CONFIGURATION=Release
      addons:
        apt:
          sources:
          - *required_sources
          packages:
          - *required_packages
          - gcc-6-multilib
          - g++-6-multilib
script:
- mkdir build
- cd build
- CC="$ACTUAL_CC" CXX="$ACTUAL_CXX" cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -DOGLTUTOR_STATIC=ON ..
- make -j2
notifications:
  email: false
